(function () {
  'use strict';

  const STORAGE_KEY = 'rede-violeta-language';
  const translations = {
    en: {
      'Idioma': 'Language',
      'Saída rápida': 'Quick exit',
      'Acessibilidade': 'Accessibility',
      'Ajuste a página do seu jeito. As preferências ficam salvas neste navegador.': 'Adjust the page to your needs. Preferences are saved in this browser.',
      'Tamanho da fonte': 'Font size',
      'Alto contraste': 'High contrast',
      'Ler conteúdo em voz alta': 'Read content aloud',
      'Pausar animações': 'Pause animations',
      'Foco visível destacado': 'Highlight keyboard focus',
      'Restaurar padrões': 'Restore defaults',
      'Resetar': 'Reset',
      'Pelo fim da violência contra a mulher': 'Together to end violence against women',
      'Projeto acadêmico desenvolvido para a': 'Academic project developed for',
      'Juntas contra a violência': 'Together against violence',
      'Um espaço seguro para desabafar, aprender e denunciar o assédio.': 'A safe space to share, learn, and report harassment.',
      'Ambiente confidencial': 'Confidential space',
      'Sigilo total': 'Complete confidentiality',
      'Seus dados nunca são compartilhados': 'Your data is never shared',
      'Denúncia anônima': 'Anonymous report',
      'Você escolhe se quer se identificar': 'You choose whether to identify yourself',
      'Conforme a LGPD': 'In compliance with Brazil’s LGPD',
      'Transmissão segura de informações': 'Secure information transmission',
      'Sem rastreamento': 'No tracking',
      'Nenhum registro de IP ou dispositivo': 'No IP address or device is recorded',
      'Informação também é proteção': 'Information is protection, too',
      'Você não está': 'You are not',
      'sozinha.': 'alone.',
      'Acolhimento': 'Support',
      'respeito • informação • proteção': 'respect • information • protection',
      'Preciso de ajuda': 'I need help',
      'Conheça os casos': 'Learn about the cases',
      'Desabafo': 'Share your feelings',
      'Conheça os Casos': 'Learn about the Cases',
      'Meu Caso': 'My Situation',
      'Recursos & Apoio': 'Resources & Support',
      'FAQ': 'FAQ',
      'Alertas': 'Alerts',
      'Uma mensagem para você': 'A message for you',
      'Você merece viver com paz, respeito, segurança e liberdade.': 'You deserve to live with peace, respect, safety, and freedom.',
      'Buscar ajuda não é sinal de fraqueza. É um passo de proteção.': 'Seeking help is not a sign of weakness. It is a step toward safety.',
      'Você não precisa enfrentar uma situação de violência sozinha.': 'You do not have to face violence alone.',
      'Informação pode ajudar você a conhecer caminhos de apoio.': 'Information can help you find ways to get support.',
      'Nenhuma forma de violência deve ser normalizada ou justificada.': 'No form of violence should be normalized or justified.',
      'Espaço de desabafo': 'A space to share',
      'Aqui você pode escrever o que está sentindo de forma livre e segura. Suas palavras são tratadas com total sigilo.': 'Here you can freely and safely write about how you feel. Your words are treated confidentially.',
      'Como você está se sentindo agora?': 'How are you feeling right now?',
      'Escreva aqui o que está sentindo… Pode ser sobre algo que aconteceu, algo que te incomoda ou simplesmente como está o seu dia. Você não está sozinha/o.': 'Write how you feel here… It can be about something that happened, something bothering you, or simply how your day is going. You are not alone.',
      'caracteres': 'characters',
      'Não foi possível registrar seu desabafo. O texto continua apenas nesta página e não foi enviado. Tente novamente quando a conexão estiver disponível; em perigo imediato, ligue 190.': 'We could not submit your message. The text remains only on this page and was not sent. Try again when a connection is available. If you are in immediate danger, call 190.',
      'Registrar meu desabafo': 'Submit my message',
      'Limpar': 'Clear',
      'Obrigada por confiar!': 'Thank you for trusting us!',
      'Seu desabafo foi registrado com segurança. Lembre-se: você merece apoio e não está sozinha/o nessa situação.': 'Your message was submitted. Remember: you deserve support and are not alone.',
      'Denúncia formalizada com protocolo.': 'Report submitted with a reference number.',
      'Não foi possível formalizar a denúncia agora. Tente novamente mais tarde ou procure um serviço de atendimento.': 'We could not submit the report right now. Try again later or contact a support service.',
      'Formalizar Denúncia': 'Submit a Report',
      'Fazer outro desabafo': 'Write another message',
      'Recursos de bem-estar': 'Well-being resources',
      'Algumas formas de cuidar de você neste momento:': 'A few ways to care for yourself right now:',
      'Respire fundo: inspire por 4 segundos, segure por 4, expire por 6.': 'Take a deep breath: inhale for 4 seconds, hold for 4, and exhale for 6.',
      'Converse com alguém de confiança — amiga/o, familiar ou colega.': 'Talk to someone you trust — a friend, family member, or colleague.',
      'Anote o que aconteceu: data, hora, local e testemunhas.': 'Write down what happened: date, time, place, and witnesses.',
      'Você tem o direito de dizer não e de buscar ajuda a qualquer momento.': 'You have the right to say no and seek help at any time.',
      'O que é o Agosto Lilás?': 'What is Purple August?',
      'Casos que marcaram a história': 'Cases that made history',
      'Conhecer casos históricos ajuda a compreender a importância da prevenção, da informação e da rede de proteção.': 'Learning about historical cases helps us understand the importance of prevention, information, and support networks.',
      'Importante:': 'Important:',
      'Meu Caso — Estou em situação de assédio?': 'My Situation — Am I experiencing harassment?',
      'apenas orientativo': 'for guidance only',
      'Pergunta': 'Question',
      'de': 'of',
      'Sim, frequentemente': 'Yes, frequently',
      'Às vezes': 'Sometimes',
      'Não': 'No',
      'Sim, sempre': 'Yes, always',
      'Sim': 'Yes',
      'Já aconteceu uma vez': 'It happened once',
      'Sim, com frequência': 'Yes, often',
      'Raramente': 'Rarely',
      'Sim, muito': 'Yes, a lot',
      'Um pouco': 'A little',
      'Às vezes tenta': 'Sometimes they try',
      'Sim, me culpo muito': 'Yes, I blame myself a lot',
      'Ver Resultado ✓': 'See Results ✓',
      'Próxima →': 'Next →',
      '← Anterior': '← Previous',
      'Situação aparentemente segura': 'Situation appears to be safe',
      'Sinal de atenção — fique alerta': 'Warning sign — stay alert',
      'Indicadores de assédio ou violência': 'Possible signs of harassment or violence',
      'Ligue': 'Call',
      'agora ou acesse': 'now or visit',
      'Refazer': 'Start over',
      'Linhas de Apoio 24h': '24-hour Support Lines',
      'Toque em uma opção para ligar agora.': 'Tap an option to call now.',
      'Ligar agora': 'Call now',
      'Criar Alerta de Abuso': 'Create an Abuse Alert',
      'Registre uma situação de risco para alertar outras pessoas. Não inclua dados pessoais de vítimas.': 'Report a risky situation to alert others. Do not include victims’ personal information.',
      'Tipo de abuso': 'Type of abuse',
      'Selecione...': 'Select...',
      'Cidade': 'City',
      'Estado': 'State',
      'Local específico (opcional)': 'Specific location (optional)',
      'Descreva a situação': 'Describe the situation',
      'Nível de urgência': 'Urgency level',
      'Baixa': 'Low',
      'Média': 'Medium',
      'Alta — risco imediato': 'High — immediate risk',
      'Publicar Alerta': 'Post Alert',
      'Todos': 'All',
      'Sexual': 'Sexual',
      'Moral': 'Emotional abuse',
      'Violência': 'Violence',
      'Virtual': 'Online',
      'Urgentes': 'Urgent',
      'Confirmar': 'Confirm',
      'Nenhum alerta encontrado para este filtro.': 'No alerts found for this filter.',
      'Carregando alertas da rede...': 'Loading community alerts...',
      'agora mesmo': 'just now',
      'min atrás': 'min ago',
      'Linha do Tempo': 'Timeline',
      'Delegacias da Mulher (DEAM)': 'Women’s Police Stations (DEAM)',
      'Encontre a DEAM mais próxima. Clique no marcador para ver endereço e telefone.': 'Find the nearest DEAM. Select a marker to see its address and phone number.',
      'Clique no marcador para ver telefone e endereço': 'Select a marker to see the phone number and address',
      'Violeta': 'Violeta',
      'Assistente da Rede Violeta · Online 💜': 'Rede Violeta Assistant · Online 💜',
      'Fale com a Violeta...': 'Talk to Violeta...',
      'Enviar': 'Send',
      'Ativar respostas faladas da Violeta': 'Enable Violeta’s spoken replies',
      'Desativar respostas faladas da Violeta': 'Disable Violeta’s spoken replies',
      'Falar com a Violeta usando o microfone': 'Talk to Violeta using the microphone',
      'Violeta está digitando…': 'Violeta is typing…',
      'Seu navegador não oferece entrada por voz. Você pode digitar sua mensagem.': 'Your browser does not support voice input. You can type your message.',
      'O acesso ao microfone foi bloqueado. Você pode digitar sua mensagem.': 'Microphone access was blocked. You can type your message.',
      'Não foi possível usar o microfone. Você pode digitar sua mensagem.': 'The microphone could not be used. You can type your message.',
      'Não foi possível iniciar o microfone. Verifique a permissão do navegador ou digite sua mensagem.': 'The microphone could not start. Check your browser permissions or type your message.',
      'Olá! 💜 Sou a Violeta, assistente da Rede Violeta. Posso ajudar você a encontrar informações sobre os canais de emergência, explicar os recursos do site ou conversar sobre situações de violência. Se houver perigo imediato, procure um local seguro e ligue 190.': 'Hello! 💜 I am Violeta, the Rede Violeta assistant. I can help you find emergency contacts, explain the resources on this site, or talk about situations involving violence. If you are in immediate danger, get to a safe place and call 190.',
      'Projeto Acadêmico — Rede Violeta': 'Academic Project — Rede Violeta',
      'O site da Rede Violeta não substitui serviços públicos, atendimento policial, médico, psicológico ou jurídico profissional.': 'Rede Violeta does not replace public services or professional police, medical, psychological, or legal assistance.',
      'Suas informações são tratadas com sigilo absoluto.': 'Your information is treated confidentially.',
      'Central da Mulher': 'Women’s Support Line',
      'Polícia': 'Police',
      'Direitos Humanos': 'Human Rights',
      'Sair rapidamente deste site e ir para uma página neutra': 'Quickly leave this site and go to a neutral page',
      'Abrir opções de acessibilidade': 'Open accessibility options',
      'Fechar opções de acessibilidade': 'Close accessibility options',
      'Diminuir fonte': 'Decrease font size',
      'Fonte padrão': 'Default font size',
      'Aumentar fonte': 'Increase font size',
      'Ativar alto contraste': 'Enable high contrast',
      'Ativar leitura de conteúdo em voz alta ao clicar nos textos': 'Enable reading text aloud when clicked',
      'Pausar animações e transições': 'Pause animations and transitions',
      'Destacar foco do teclado': 'Highlight keyboard focus',
      'Telefone': 'Phone',
      'Endereço': 'Address',
      'Canais de apoio 24h — Agosto Lilás pelo seu direito de dizer NÃO': '24-hour support lines — Purple August and your right to say NO',
      'é um projeto acadêmico criado para informar,\n        acolher e apresentar caminhos de apoio para mulheres que estejam passando\n        por situações de violência.': 'is an academic project created to inform, support, and connect women experiencing violence with ways to get help.',
      'Busque apoio psicológico; muitas cidades oferecem serviço gratuito (CAPS).': 'Seek psychological support; many cities offer free services (CAPS).',
      'é um movimento nacional de conscientização contra a violência doméstica e sexual. Instituído em agosto — mês da Lei Maria da Penha (Lei nº 11.340/2006, sancionada em 07/08/2006) — o movimento usa o roxo/lilás como símbolo de resistência e esperança.': 'is a national awareness campaign against domestic and sexual violence. Held in August, the month of the Maria da Penha Law (Law No. 11,340/2006, enacted on August 7, 2006), it uses purple and lilac as symbols of resistance and hope.',
      '1 mulher é vítima de violência a cada 6 minutos': 'One woman experiences violence every 6 minutes',
      '. Falar sobre isso é o primeiro passo para mudar.': '. Talking about it is the first step toward change.',
      'A socialite mineira foi assassinada pelo então namorado. O julgamento provocou grande debate social sobre a culpabilização da vítima e impulsionou discussões importantes sobre a violência contra mulheres.': 'The socialite from Minas Gerais was murdered by her then-boyfriend. The trial sparked public debate about victim-blaming and important discussions about violence against women.',
      '💜 O caso contribuiu para debates históricos sobre violência contra mulheres e sobre argumentos que culpabilizam vítimas.': '💜 The case contributed to historic debates about violence against women and arguments that blame victims.',
      'A atriz e bailarina foi assassinada em 1992. O caso provocou grande mobilização social e a participação de sua mãe, Gloria Perez, em mudanças na legislação penal.': 'The actress and dancer was murdered in 1992. The case prompted widespread public mobilization and her mother, Gloria Perez, helped bring about changes to criminal law.',
      '💜 O caso mostra como a mobilização social pode contribuir para mudanças importantes na legislação.': '💜 The case shows how public mobilization can contribute to important legal changes.',
      'Aos 15 anos, Eloá foi mantida em cárcere privado pelo ex-namorado em Santo André, SP. O caso teve grande repercussão nacional e o agressor foi condenado a 98 anos e 8 meses.': 'At 15, Eloá was held captive by her ex-boyfriend in Santo André, São Paulo. The case drew national attention and the perpetrator was sentenced to 98 years and 8 months.',
      '💜 O caso reforça a importância de reconhecer situações de controle e ameaça e buscar ajuda.': '💜 The case highlights the importance of recognizing control and threats and seeking help.',
      'Eliza desapareceu em 2010. O caso envolveu o então goleiro Bruno Fernandes e teve grande repercussão nacional, evidenciando a importância de redes de proteção.': 'Eliza disappeared in 2010. The case involved goalkeeper Bruno Fernandes and attracted national attention, underscoring the importance of support networks.',
      'A advogada foi assassinada em 2010. O caso foi julgado pelo Tribunal do Júri de Guarulhos — primeiro julgamento televisionado ao vivo no Brasil. O agressor foi condenado a 22 anos e 8 meses.': 'The lawyer was murdered in 2010. The case was tried by the Guarulhos jury court, the first trial broadcast live in Brazil. The perpetrator was sentenced to 22 years and 8 months.',
      'Assédio é qualquer comportamento indesejado que cause constrangimento, humilhação, intimidação ou sofrimento. Pode ser físico, verbal, virtual ou psicológico.': 'Harassment is any unwanted behavior that causes embarrassment, humiliation, intimidation, or distress. It may be physical, verbal, online, or psychological.',
      'é culpa de quem sofre. Independentemente de roupa, comportamento ou relação com o agressor.': 'is the perpetrator’s fault, regardless of clothing, behavior, or relationship with the perpetrator.',
      'Exposição repetida a situações humilhantes ou constrangedoras no ambiente de trabalho.': 'Repeated exposure to humiliating or embarrassing situations at work.',
      'Ser ignorada/o sistematicamente por colegas ou superiores.': 'Being repeatedly ignored by colleagues or supervisors.',
      'Receber tarefas impossíveis de cumprir para ser culpabilizada/o.': 'Being given impossible tasks and then blamed for not completing them.',
      'Sofrer piadas, apelidos ofensivos ou humilhações na frente de outros.': 'Being subjected to jokes, offensive nicknames, or humiliation in front of others.',
      'Ter méritos negados ou trabalho atribuído a outra pessoa.': 'Having your achievements denied or your work credited to someone else.',
      'Ameaças constantes de demissão sem motivo justificado.': 'Constant threats of dismissal without a valid reason.',
      'Isolamento forçado ou retirada de responsabilidades sem explicação.': 'Being isolated or stripped of responsibilities without explanation.',
      'Conduta de natureza sexual não desejada, que constranja ou cause desconforto.': 'Unwanted sexual behavior that causes embarrassment or discomfort.',
      'Comentários, piadas ou insinuações de cunho sexual.': 'Sexual comments, jokes, or innuendo.',
      'Toques não consentidos em qualquer parte do corpo.': 'Unwanted touching of any part of the body.',
      'Convites insistentes para encontros após rejeição clara.': 'Repeated invitations to meet after a clear refusal.',
      'Envio de imagens, vídeos ou mensagens de conteúdo sexual não solicitado.': 'Sending unsolicited sexual images, videos, or messages.',
      'Chantagem com vantagens profissionais em troca de favores sexuais.': 'Blackmail involving professional benefits in exchange for sexual favors.',
      'Perseguição, humilhação ou ameaças realizadas por meios digitais.': 'Stalking, humiliation, or threats carried out online.',
      'Mensagens ofensivas, ameaças ou difamação em redes sociais.': 'Offensive messages, threats, or defamation on social media.',
      'Compartilhamento de fotos ou vídeos íntimos sem consentimento (revenge porn).': 'Sharing intimate photos or videos without consent (image-based sexual abuse).',
      'Monitoramento excessivo de perfis, localização ou atividades online.': 'Excessive monitoring of profiles, location, or online activity.',
      'Comportamentos controladores e abusivos dentro de relações familiares ou afetivas.': 'Controlling and abusive behavior in family or intimate relationships.',
      'Controle de com quem você fala, sai ou se relaciona.': 'Controlling whom you talk to, go out with, or have relationships with.',
      'Críticas constantes, xingamentos ou desvalorização.': 'Constant criticism, insults, or belittling.',
      'Ameaças veladas ou explícitas de agressão física.': 'Implicit or explicit threats of physical violence.',
      'Controle financeiro — impedir acesso ao próprio dinheiro.': 'Financial control — preventing someone from accessing their own money.',
      'Comportamento agressivo e repetitivo contra estudantes em ambiente escolar.': 'Repeated aggressive behavior toward students in a school setting.',
      'Sinais de alerta em você mesma/o': 'Warning signs you may notice in yourself',
      'Se você está passando por assédio, pode notar alguns desses efeitos:': 'If you are experiencing harassment, you may notice some of these effects:',
      'Ansiedade ou medo constante': 'Ongoing anxiety or fear',
      'Dores físicas sem causa aparente': 'Physical pain without an apparent cause',
      'Dificuldade de concentração': 'Difficulty concentrating',
      'O que fazer se isso acontecer comigo?': 'What can I do if this happens to me?',
      '— especialmente se houver risco de violência.': '— especially if there is a risk of violence.',
      '— alguém que tenha presenciado situações.': '— someone who witnessed the events.',
      '— RH, direção escolar, conselho tutelar, etc.': '— Human Resources, school leadership, child protection services, etc.',
      'Registre boletim de ocorrência': 'File a police report',
      '— na delegacia da mulher ou online.': '— at a women’s police station or online.',
      'Procure apoio jurídico e psicológico': 'Seek legal and psychological support',
      'Eventos históricos relevantes para a legislação de proteção à mulher.': 'Historical events relevant to laws protecting women.',
      'Responda as perguntas abaixo com sinceridade. O resultado é': 'Answer the questions below honestly. The result is',
      'e não substitui apoio profissional.': 'and does not replace professional support.',
      '1. Alguém faz comentários, piadas ou gestos de conteúdo sexual ou íntimo sem sua permissão?': '1. Does anyone make sexual or intimate comments, jokes, or gestures without your consent?',
      '2. Você sente medo ou ansiedade quando vai ao trabalho, escola ou se relaciona com alguém específico?': '2. Do you feel afraid or anxious going to work or school, or when interacting with a particular person?',
      '3. Alguém te pressiona, chantageia ou ameaça para obter algum favor, presença ou contato?': '3. Does anyone pressure, blackmail, or threaten you to get a favor, your presence, or contact?',
      '4. Você recebe mensagens, ligações ou contatos insistentes mesmo depois de pedir que parem?': '4. Do you receive repeated messages, calls, or contact after asking someone to stop?',
      '5. Alguém te humilha, grita, te diminui ou critica na frente de outras pessoas?': '5. Does anyone humiliate, yell at, belittle, or criticize you in front of others?',
      '6. Você evita certos lugares, situações ou pessoas por se sentir insegura/o?': '6. Do you avoid certain places, situations, or people because you feel unsafe?',
      '7. Alguém controla o que você faz, com quem fala, onde vai ou como se veste?': '7. Does anyone control what you do, whom you talk to, where you go, or what you wear?',
      '8. Você se culpa por situações em que foi tratada/o de forma desrespeitosa?': '8. Do you blame yourself for situations in which you were treated disrespectfully?',
      'Orientação, denúncia e encaminhamento. Gratuito, 24h.': 'Guidance, reporting, and referrals. Free, 24 hours a day.',
      'Emergências e ocorrências em andamento.': 'Emergencies and incidents in progress.',
      'Violações de direitos, inclusive crianças e adolescentes.': 'Human rights violations, including those involving children and teenagers.',
      'Assistência jurídica gratuita para quem não pode pagar advogado.': 'Free legal assistance for people who cannot afford a lawyer.',
      'Apoio Psicológico Gratuito': 'Free psychological support',
      'Acesse os sites oficiais para encontrar atendimento perto de você.': 'Visit official websites to find support near you.',
      'Denúncia e apoio para crimes e violências na internet.': 'Reporting and support for online crimes and abuse.',
      'Nenhuma pergunta encontrada. Tente outro termo.': 'No questions found. Try another search term.',
      'Onde e como o assédio mais acontece': 'Where and how harassment most often happens',
      'Fórum Brasileiro de Segurança Pública 2025': 'Brazilian Public Security Forum 2025',
      'espaço seguro para desabafar': 'safe space to share',
      'Projeto Acadêmico — Rede Violeta': 'Academic Project — Rede Violeta',
      'Este site foi desenvolvido como projeto acadêmico para a Faculdade Cruzeiro do Sul, com finalidade educativa e de conscientização sobre violência contra a mulher.': 'This website was developed as an academic project for Faculdade Cruzeiro do Sul to educate and raise awareness about violence against women.',
      'A Rede Violeta não substitui serviços públicos, atendimento policial, médico, psicológico ou jurídico profissional.': 'Rede Violeta does not replace public services or professional police, medical, psychological, or legal assistance.',
      '🎙️ Ouvindo... fale agora.': '🎙️ Listening... speak now.',
      'Selecione uma opção antes de avançar.': 'Select an option before continuing.',
      'Escreva algo antes de registrar seu desabafo. 💙': 'Write something before submitting your message. 💙',
      'Suas respostas não indicam sinais fortes de assédio no momento. Continue atenta/o e lembre-se: qualquer desconforto merece atenção. Fique segura/o e cuide-se!': 'Your answers do not currently indicate strong signs of harassment. Stay aware and remember: any discomfort deserves attention. Stay safe and take care!',
      'Suas respostas indicam situações que merecem atenção. Algumas experiências que você relatou podem configurar assédio. Conversar com alguém de confiança ou um profissional pode ajudar a esclarecer a situação.': 'Your answers point to situations that deserve attention. Some experiences you described may constitute harassment. Talking with someone you trust or a professional may help clarify the situation.',
      'Suas respostas indicam que você pode estar em situação de assédio ou violência. Você não está sozinha/o e há apoio disponível. Busque ajuda agora — use os canais abaixo ou a aba Fazer Denúncia.': 'Your answers suggest you may be experiencing harassment or violence. You are not alone, and support is available. Seek help now using the contacts below or the report tab.',
      'Violência Doméstica': 'Domestic Violence',
      'Assédio Sexual': 'Sexual Harassment',
      'Assédio Moral': 'Workplace Bullying',
      'Assédio Virtual / Cyberbullying': 'Online Harassment / Cyberbullying',
      'Perseguição (Stalking)': 'Stalking',
      'Importunação Sexual': 'Sexual Harassment',
      'Violência Física': 'Physical Violence',
      'Assédio Virtual (Cyberbullying / Stalking Online)': 'Online Harassment (Cyberbullying / Online Stalking)',
      'Assédio Doméstico / Familiar': 'Domestic / Family Abuse',
      'Assédio Escolar (Bullying)': 'School Bullying',
      'CAPS — Centro de Atenção Psicossocial': 'CAPS — Psychosocial Care Center',
      'UBS — Unidade Básica de Saúde': 'UBS — Primary Health Care Unit',
      'Delegacia da Mulher (DEAM)': 'Women’s Police Station (DEAM)',
      'O que diferencia assédio de violência?': 'What is the difference between harassment and violence?',
      'Posso denunciar de forma anônima?': 'Can I report anonymously?',
      'Preciso de advogado para denunciar?': 'Do I need a lawyer to file a report?',
      'A Lei Maria da Penha protege apenas mulheres cisgênero?': 'Does the Maria da Penha Law protect only cisgender women?',
      'O que acontece depois que eu denuncio?': 'What happens after I file a report?',
      'Posso retirar uma denúncia depois?': 'Can I withdraw a report later?',
      'Como provar assédio no trabalho?': 'How can I document workplace harassment?',
      'O que é uma Medida Protetiva de Urgência?': 'What is an Emergency Protective Order?',
      'Assédio virtual / online é crime?': 'Is online harassment a crime?',
      'Você pode mudar essa opção depois.': 'You can change this setting later.',
      'Mudar idioma': 'Change language',
      'Indicadores de segurança': 'Safety indicators',
      'AGOSTO LILÁS 2026': 'PURPLE AUGUST 2026',
      'Agosto Lilás 2026': 'Purple August 2026',
      'Agosto Lilás': 'Purple August',
      'O que é assédio?': 'What is harassment?',
      'é um comportamento repetido e indesejado de natureza sexual, moral ou psicológica.': 'is repeated, unwanted behavior of a sexual, moral, or psychological nature.',
      'pode ser um único ato físico, sexual, psicológico, patrimonial ou moral.': 'can be a single physical, sexual, psychological, financial, or moral act.',
      'Ambos são crimes — a diferença está na forma e na frequência, mas os dois merecem denúncia.': 'Both may be crimes. They differ in form and frequency, but both deserve to be reported.',
      'aceitam denúncias anônimas. A identidade não é necessária para que a denúncia seja investigada.': 'accept anonymous reports. Your identity is not required for an investigation.',
      'Você pode registrar sozinha/o na delegacia ou online. Para processos judiciais é recomendado, mas a': 'You can file a report on your own at a police station or online. Legal representation is recommended for court proceedings, but the',
      'oferece assistência jurídica': 'provides legal assistance',
      'para quem não tem condições de contratar advogado particular.': 'to people who cannot afford a private lawyer.',
      'O STJ e o STF entendem que a Lei Maria da Penha protege': 'The Superior Court of Justice and the Supreme Court have ruled that the Maria da Penha Law protects',
      ', pois o critério é gênero feminino, não biológico. Homens cisgêneros podem recorrer ao Código Penal e à Lei nº 13.772/2018 em casos de violência doméstica.': ', because the criterion is female gender, not biological sex. Cisgender men may seek protection under the Penal Code and Law No. 13,772/2018 in cases of domestic violence.',
      '1. A delegacia abre um Inquérito Policial.': '1. The police open an investigation.',
      '2. O Ministério Público recebe o inquérito e pode oferecer denúncia criminal.': '2. The Public Prosecutor’s Office receives the investigation and may file criminal charges.',
      '3. Você pode solicitar': '3. You may request',
      'Medidas Protetivas de Urgência': 'Emergency Protective Orders',
      '4. O juiz decide sobre as medidas em até 48h.': '4. A judge decides on the measures within 48 hours.',
      'não pode ser retirada': 'cannot be withdrawn',
      'pela vítima após o processo iniciado — cabe ao Estado prosseguir. Isso protege a vítima de pressões do agressor. A retratação só é possível antes do recebimento da denúncia pelo juiz, mediante audiência.': 'by the victim after proceedings begin; the state is responsible for continuing the case. This protects victims from pressure by the abuser. Withdrawal is possible only before a judge accepts the charges, at a court hearing.',
      'Guarde prints de mensagens, e-mails, registros de chamadas. Anote datas, horários e o que foi dito. Identifique testemunhas. Registre ocorrência no RH com protocolo. Em seguida, procure a Delegacia do Trabalho (MTE) ou ajuíze ação na Justiça do Trabalho. O assédio moral é ilícito civil (art. 186 CC) e pode resultar em demissão por justa causa do agressor.': 'Keep screenshots of messages, emails, and call logs. Record dates, times, and what was said, and identify witnesses. File a documented report with Human Resources, then contact the Ministry of Labor or file a labor claim. Workplace bullying is a civil offense and may lead to the perpetrator’s dismissal for cause.',
      'É uma determinação judicial que pode: proibir o agressor de se aproximar da vítima; proibi-lo de contato por qualquer meio; retirá-lo do lar; suspender porte de arma. É solicitada ao registrar o B.O. e decidida pelo juiz em até 48 horas. Descumprir medida protetiva é crime com pena de 3 meses a 2 anos de prisão (art. 24-A da Lei Maria da Penha).': 'It is a court order that can prohibit an abuser from approaching or contacting the victim, remove the abuser from the home, or suspend their firearm permit. It may be requested when filing a police report, and a judge decides within 48 hours. Violating a protective order is a crime punishable by 3 months to 2 years in prison under Article 24-A of the Maria da Penha Law.',
      'Sim. A Lei nº 13.772/2018 criminaliza o registro não autorizado de conteúdo íntimo. A Lei nº 13.718/2018 criou o crime de importunação sexual online. Compartilhamento de fotos íntimas sem consentimento (revenge porn) é crime com pena de 1 a 5 anos. Denuncie também pelo SaferNet.': 'Yes. Law No. 13,772/2018 criminalizes unauthorized recording of intimate content. Law No. 13,718/2018 created the crime of online sexual harassment. Sharing intimate images without consent is also a crime, punishable by 1 to 5 years in prison. Reports can also be made to SaferNet.',
      'Criação de perfis falsos para assediar ou difamar.': 'Creating fake profiles to harass or defame someone.',
      'Exclusão social online organizada por um grupo.': 'Coordinated online social exclusion by a group.',
      'Ciúmes excessivos e cobranças de localização a todo momento.': 'Excessive jealousy and constant demands to share your location.',
      'Apelidos ofensivos, ridicularização ou exclusão do grupo.': 'Offensive nicknames, ridicule, or exclusion from the group.',
      'Agressões físicas, empurrões ou destruição de objetos.': 'Physical attacks, pushing, or destruction of belongings.',
      'Ameaças ou chantagem por materiais escolares, dinheiro ou favores.': 'Threats or blackmail over school supplies, money, or favors.',
      'Difamação ou fofocas para isolar a vítima socialmente.': 'Defamation or gossip intended to socially isolate the victim.',
      'Insônia ou pesadelos': 'Insomnia or nightmares',
      '— salve prints, e-mails, mensagens, datas e horários.': '— save screenshots, emails, messages, dates, and times.',
      'Não confronte sozinha/o': 'Do not confront the person alone',
      'Comunique à instituição': 'Report it to the organization',
      '188 — CVV': '188 — CVV (Life Valuation Center)',
      'Centro de Valorização da Vida. Escuta e apoio emocional.': 'Brazilian Life Valuation Center. Emotional support and someone to listen.',
      'Apoio Jurídico Gratuito': 'Free legal support',
      'Defensoria Pública': 'Public Defender’s Office',
      'OAB — Ordem dos Advogados': 'OAB — Brazilian Bar Association',
      'Núcleos de prática jurídica e atendimento pro bono em muitas seccionais.': 'Legal clinics and pro bono services are available at many local bar associations.',
      'Núcleos Universitários': 'University legal clinics',
      'Clínicas jurídicas de faculdades oferecem atendimento gratuito supervisionado.': 'University law clinics provide free, supervised assistance.',
      'Serviço público gratuito de saúde mental. Para orientação, ligue 136 (Disque Saúde).': 'Free public mental health service. For guidance, call 136 (Health Line).',
      'Centro de Referência em Assistência Social. Para localizar atendimento, ligue 121 (Disque Social).': 'Social Assistance Reference Center. To find a service, call 121 (Social Services Line).',
      'Solicite encaminhamento para psicólogo pelo SUS. Para orientação, ligue 136 (Disque Saúde).': 'Ask Brazil’s public health system (SUS) for a referral to a psychologist. For guidance, call 136 (Health Line).',
      'Registro discreto de ocorrências diretamente pelo celular.': 'Discreetly record incidents on your phone.',
      'denúncias e orientações online.': 'online reports and guidance.',
      'Consulta gratuita de processos e orientações jurídicas.': 'Free case searches and legal information.',
      'O Agosto Lilás': 'Purple August',
      '💜 A história reforça a importância de redes de proteção e de canais para pedir ajuda.': '💜 This story highlights the importance of support networks and channels for seeking help.',
      '💜 O caso evidencia a importância da investigação, da Justiça e do acolhimento às famílias das vítimas.': '💜 This case highlights the importance of investigation, justice, and support for victims’ families.',
      'os casos apresentados são fatos históricos utilizados exclusivamente para fins educativos e de conscientização.': 'the cases presented are historical events used solely for educational and awareness purposes.',
      'Especializada em violência doméstica. Ligue 180 para localizar a mais próxima.': 'Specialized in domestic violence. Call 180 to find the nearest station.',
      '— muitos são gratuitos.': '— many are free.',
      'dos casos de violência ocorrem na': 'of violence cases happen at the',
      'residência': 'home',
      'da vítima': 'of the victim',
      'acontecem em': 'happen on',
      'vias públicas': 'public streets',
      ', ruas e espaços abertos': ', roads, and open spaces',
      'dos agressores são': 'of perpetrators are',
      'parceiros ou ex-parceiros': 'current or former partners',
      'Residência — 65%': 'Home — 65%',
      'Principal cenário de violência doméstica e psicológica. A vítima convive com o agressor.': 'The primary setting for domestic and psychological violence, where the victim lives with the abuser.',
      'Via pública — 13%': 'Public streets — 13%',
      'Ruas, praças, feiras e pontos de ônibus. Maior incidência nos horários de pico.': 'Streets, squares, markets, and bus stops. Incidents are more frequent during rush hour.',
      'Praticado por colegas, superiores ou clientes. Muitas vezes silenciado por medo de demissão.': 'Committed by colleagues, supervisors, or customers, and often silenced by fear of losing a job.',
      'Transporte público — 4%': 'Public transportation — 4%',
      'Metrô, ônibus e terminais. Especialmente intenso nos horários de pico.': 'Subways, buses, and terminals. Incidents are especially frequent during rush hour.',
      'Afeta principalmente jovens e adolescentes; pode começar no ambiente virtual.': 'It mainly affects young people and teenagers and can begin online.',
      '— Metrô Linha 2-Verde': '— Green Line 2 subway',
      'Relatos recorrentes de importunação sexual nos vagões entre as estações Paraíso e Ana Rosa nos horários de pico.': 'Repeated reports of sexual harassment in train cars between Paraíso and Ana Rosa stations during rush hour.',
      '1h atrás': '1 hour ago',
      '— Bairro Água Verde': '— Água Verde neighborhood',
      'Homem seguindo mulheres que saem do trabalho no período noturno. Comportamento identificado em mais de uma ocasião.': 'A man has been following women leaving work at night. This behavior has been reported more than once.',
      '— Bairro Santa Efigênia': '— Santa Efigênia neighborhood',
      'Situação de violência doméstica em andamento relatada por vizinhas. Pedido de apoio e orientação à comunidade.': 'Neighbors reported an ongoing domestic violence situation and requested community support and guidance.',
      '2h atrás': '2 hours ago',
      '— Setor Bancário Sul — empresa privada': '— South Banking Sector — private company',
      'Supervisora humilha funcionárias publicamente em reuniões, atribui erros alheios a elas e ameaça demissão sem justificativa. Pelo menos 5 relatos confirmados.': 'A supervisor publicly humiliates employees in meetings, blames them for others’ mistakes, and threatens unjustified dismissal. At least five reports have been confirmed.',
      '3h atrás': '3 hours ago',
      'Grupo no Telegram compartilha fotos e vídeos íntimos de mulheres sem consentimento. Vítimas identificadas já acionaram a SaferNet.': 'A Telegram group is sharing intimate photos and videos of women without consent. Identified victims have contacted SaferNet.',
      '4h atrás': '4 hours ago',
      'Perfis falsos criados para assediar mulheres com mensagens íntimas não solicitadas. Múltiplas vítimas relataram o mesmo padrão.': 'Fake profiles are being used to send women unsolicited intimate messages. Multiple victims have reported the same pattern.',
      '5h atrás': '5 hours ago',
      'O que fazer se isso acontecer comigo?': 'What should I do if this happens to me?',
      'Assédio': 'Harassment',
      'O assédio nunca': 'Harassment is never',
      'prints de mensagens': 'screenshots of messages',
      'testemunhas': 'witnesses',
      'É uma determinação judicial que pode: proibir o agressor de se aproximar da vítima; proibi-lo de contato por qualquer meio; retirá-lo do lar; suspender porte de arma. É solicitada ao registrar o B.O. e decidida pelo juiz em até': 'It is a court order that can prohibit the abuser from approaching or contacting the victim, remove the abuser from the home, or suspend a firearm permit. It may be requested when filing a police report, and a judge decides within',
      'Descumprir medida protetiva é crime com pena de 3 meses a 2 anos de prisão (art. 24-A da Lei Maria da Penha).': 'Violating a protective order is a crime punishable by 3 months to 2 years in prison under Article 24-A of the Maria da Penha Law.',
      'criminaliza o registro não autorizado de conteúdo íntimo. A': 'criminalizes unauthorized recording of intimate content. Law No. 13,718/2018',
      'criou o crime de importunação sexual online. Compartilhamento de fotos íntimas sem consentimento (': 'created the crime of online sexual harassment. Sharing intimate images without consent (',
      ') é crime com pena de 1 a 5 anos. Denuncie também pelo': ') is a crime punishable by 1 to 5 years in prison. You can also report it to',
      'O assédio moral é ilícito civil': 'Workplace bullying is a civil offense',
      'Não para o Boletim de Ocorrência.': 'No, not to file a police report.',
      'Não.': 'No.',
      'Inquérito Policial': 'police investigation',
      'ação penal pública': 'public criminal prosecution',
      '(como os previstos na Lei Maria da Penha), a denúncia': '(such as those covered by the Maria da Penha Law), the report',
      ', e-mails, registros de chamadas. Anote datas, horários e o que foi dito. Identifique': ', emails, and call logs. Record dates, times, and what was said. Identify',
      '. Registre ocorrência no RH com protocolo. Em seguida, procure a': '. File a documented report with Human Resources, then contact the',
      'ou ajuíze ação na': 'or file a claim with the',
      'Justiça do Trabalho': 'Labor Court',
      '. O assédio moral é ilícito civil (art. 186 CC) e pode resultar em demissão por justa causa do agressor.': '. Workplace bullying is a civil offense (Article 186 of the Civil Code) and may lead to the perpetrator’s dismissal for cause.',
      'É uma determinação judicial que pode: proibir o agressor de se aproximar': 'It is a court order that can prohibit the abuser from approaching',
      'of the victim; proibi-lo de contato por qualquer meio; retirá-lo do lar; suspender porte de arma. É solicitada ao registrar o B.O. e decidida pelo juiz em até': 'of the victim, prohibit any contact, remove the abuser from the home, or suspend their firearm permit. It may be requested when filing a police report, and a judge decides within',
      '. Descumprir medida protetiva é crime com pena de 3 meses a 2 anos de prisão (art. 24-A da Lei Maria da Penha).': '. Violating a protective order is a crime punishable by 3 months to 2 years in prison under Article 24-A of the Maria da Penha Law.',
      'criminaliza o registro não autorizado de conteúdo íntimo. A': 'criminalizes unauthorized recording of intimate content. Law No. 13,718/2018',
      'criou o crime de importunação sexual online. Compartilhamento de fotos íntimas sem consentimento (': 'created the crime of online sexual harassment. Sharing intimate images without consent (',
      ') é crime com pena de 1 a 5 anos. Denuncie também pelo': ') is a crime punishable by 1 to 5 years in prison. You can also report it to',
      'Homem encosta e faz comentários obscenos em mulheres que aguardam ônibus no período da tarde. Relatado por passageiras em diferentes dias.': 'A man touches women and makes obscene comments to women waiting for the bus in the afternoon. Passengers reported this on different days.',
      '6h atrás': '6 hours ago',
      'Mulher agredida fisicamente por parceiro em via pública. Vizinhos chamaram a PM. Vítima está em abrigo. Caso em acompanhamento pela Delegacia da Mulher.': 'A woman was physically assaulted by her partner in public. Neighbors called the police. She is in a shelter, and the Women’s Police Station is following the case.',
      '8h atrás': '8 hours ago',
      'Ex-aluno persegue estudante dentro do campus, manda mensagens ameaçadoras e aparece em locais que ela frequenta. Caso registrado na ouvidoria da universidade.': 'A former student is stalking a student on campus, sending threatening messages, and appearing where she goes. The case was reported to the university ombuds office.',
      '10h atrás': '10 hours ago',
      'Grupo de homens abordando mulheres de forma agressiva na orla. Situação especialmente intensa nos finais de semana.': 'A group of men is aggressively approaching women along the waterfront. The situation is especially serious on weekends.',
      'Mulher foi agredida com socos pelo companheiro após tentar terminar o relacionamento. Filho menor de idade presenciou. Medida protetiva solicitada.': 'A woman was punched by her partner after trying to end the relationship. Her minor child witnessed the assault. A protective order was requested.',
      '— Praia de Jurerê': '— Jurerê Beach',
      'Homens abordam mulheres que estão sozinhas na praia, fazem comentários sexuais e seguem mesmo após pedido de afastamento. Situações repetidas nos fins de semana.': 'Men approach women who are alone at the beach, make sexual comments, and follow them after being told to stop. These incidents recur on weekends.',
      'Mulheres relatam apalpamentos e comentários sexuais na feira, especialmente em dias de maior movimento. Policiamento pedido por feirantes.': 'Women report groping and sexual comments at the market, especially on busy days. Vendors have requested increased police patrols.',
      '— Escritório de advocacia — Centro': '— Law office — downtown',
      'Advogada relata que sócio faz comentários sobre seu corpo e envia mensagens com conotação sexual. Dois outros funcionários testemunharam situações.': 'A lawyer reports that a partner comments on her body and sends sexually suggestive messages. Two other employees witnessed incidents.',
      '— Setor Jardim América': '— Jardim América district',
      'Moradora relata agressões verbais e físicas frequentes. Tentou registrar BO, mas se sentiu intimidada. Vizinhos solicitam apoio de assistência social.': 'A resident reports frequent verbal and physical abuse. She tried to file a police report but felt intimidated. Neighbors are requesting social assistance.',
      'Funcionárias relatam assédio moral sistemático por parte de gerência. Situação já reportada ao RH sem resolução.': 'Employees report systematic workplace bullying by management. The situation was reported to Human Resources but remains unresolved.',
      '— Hospital público regional': '— Regional public hospital',
      'Grupo de alunos cria memes ofensivos com fotos de colegas do sexo feminino e circula em grupos de turma. Direção da escola foi comunicada.': 'A group of students created offensive memes using photos of female classmates and shared them in class group chats. The school administration has been notified.',
      'Assédio': 'Harassment',
      'Não para o Boletim de Ocorrência.': 'No, not to file a police report.',
      'gratuita': 'free',
      'mulheres trans e travestis': 'trans women and travestis',
      'Inquérito Policial': 'police investigation',
      'ação penal pública': 'public criminal prosecution',
      '(como os previstos na Lei Maria da Penha), a denúncia': '(such as those covered by the Maria da Penha Law), the report',
      'Justiça do Trabalho': 'Labor Court',
      'Não.': 'No.',
      '6h atrás': '6 hours ago',
      '8h atrás': '8 hours ago',
      '10h atrás': '10 hours ago',
      '16h atrás': '16 hours ago',
      '18h atrás': '18 hours ago',
      '20h atrás': '20 hours ago',
      '1d atrás': '1 day ago',
      'Outro': 'Other',
      'Alta': 'High',
      'Média': 'Medium',
      'Baixa': 'Low'
    },
    es: {
      'Idioma': 'Idioma',
      'Saída rápida': 'Salida rápida',
      'Acessibilidade': 'Accesibilidad',
      'Ajuste a página do seu jeito. As preferências ficam salvas neste navegador.': 'Ajusta la página a tus necesidades. Las preferencias se guardan en este navegador.',
      'Tamanho da fonte': 'Tamaño de fuente',
      'Alto contraste': 'Alto contraste',
      'Ler conteúdo em voz alta': 'Leer el contenido en voz alta',
      'Pausar animações': 'Pausar animaciones',
      'Foco visível destacado': 'Resaltar el foco del teclado',
      'Restaurar padrões': 'Restaurar valores predeterminados',
      'Resetar': 'Restablecer',
      'Pelo fim da violência contra a mulher': 'Por el fin de la violencia contra las mujeres',
      'Projeto acadêmico desenvolvido para a': 'Proyecto académico desarrollado para',
      'Juntas contra a violência': 'Juntas contra la violencia',
      'Um espaço seguro para desabafar, aprender e denunciar o assédio.': 'Un espacio seguro para expresarte, aprender y denunciar el acoso.',
      'Ambiente confidencial': 'Entorno confidencial',
      'Sigilo total': 'Confidencialidad total',
      'Seus dados nunca são compartilhados': 'Tus datos nunca se comparten',
      'Denúncia anônima': 'Denuncia anónima',
      'Você escolhe se quer se identificar': 'Tú eliges si quieres identificarte',
      'Conforme a LGPD': 'De conformidad con la LGPD de Brasil',
      'Transmissão segura de informações': 'Transmisión segura de información',
      'Sem rastreamento': 'Sin seguimiento',
      'Nenhum registro de IP ou dispositivo': 'No se registra la IP ni el dispositivo',
      'Informação também é proteção': 'La información también protege',
      'Você não está': 'No estás',
      'sozinha.': 'sola.',
      'Acolhimento': 'Apoyo',
      'respeito • informação • proteção': 'respeto • información • protección',
      'Preciso de ajuda': 'Necesito ayuda',
      'Conheça os casos': 'Conoce los casos',
      'Desabafo': 'Desahogo',
      'Conheça os Casos': 'Conoce los casos',
      'Meu Caso': 'Mi situación',
      'Recursos & Apoio': 'Recursos y apoyo',
      'Alertas': 'Alertas',
      'Uma mensagem para você': 'Un mensaje para ti',
      'Você merece viver com paz, respeito, segurança e liberdade.': 'Mereces vivir con paz, respeto, seguridad y libertad.',
      'Buscar ajuda não é sinal de fraqueza. É um passo de proteção.': 'Pedir ayuda no es señal de debilidad. Es un paso para protegerte.',
      'Você não precisa enfrentar uma situação de violência sozinha.': 'No tienes que enfrentar una situación de violencia sola.',
      'Informação pode ajudar você a conhecer caminhos de apoio.': 'La información puede ayudarte a encontrar apoyo.',
      'Nenhuma forma de violência deve ser normalizada ou justificada.': 'Ninguna forma de violencia debe normalizarse ni justificarse.',
      'Espaço de desabafo': 'Espacio para expresarte',
      'Aqui você pode escrever o que está sentindo de forma livre e segura. Suas palavras são tratadas com total sigilo.': 'Aquí puedes escribir libremente y con seguridad cómo te sientes. Tus palabras se tratan de forma confidencial.',
      'Como você está se sentindo agora?': '¿Cómo te sientes ahora?',
      'Escreva aqui o que está sentindo… Pode ser sobre algo que aconteceu, algo que te incomoda ou simplesmente como está o seu dia. Você não está sozinha/o.': 'Escribe aquí cómo te sientes… Puede ser sobre algo que pasó, algo que te preocupa o simplemente cómo va tu día. No estás sola.',
      'caracteres': 'caracteres',
      'Não foi possível registrar seu desabafo. O texto continua apenas nesta página e não foi enviado. Tente novamente quando a conexão estiver disponível; em perigo imediato, ligue 190.': 'No pudimos enviar tu mensaje. El texto permanece solo en esta página y no se envió. Inténtalo de nuevo cuando haya conexión. Si estás en peligro inmediato, llama al 190.',
      'Registrar meu desabafo': 'Enviar mi mensaje',
      'Limpar': 'Limpiar',
      'Obrigada por confiar!': '¡Gracias por confiar!',
      'Seu desabafo foi registrado com segurança. Lembre-se: você merece apoio e não está sozinha/o nessa situação.': 'Tu mensaje se envió de forma segura. Recuerda: mereces apoyo y no estás sola.',
      'Denúncia formalizada com protocolo.': 'Denuncia enviada con número de referencia.',
      'Não foi possível formalizar a denúncia agora. Tente novamente mais tarde ou procure um serviço de atendimento.': 'No pudimos enviar la denuncia ahora. Inténtalo más tarde o busca un servicio de atención.',
      'Formalizar Denúncia': 'Presentar denuncia',
      'Fazer outro desabafo': 'Escribir otro mensaje',
      'Recursos de bem-estar': 'Recursos de bienestar',
      'Algumas formas de cuidar de você neste momento:': 'Algunas formas de cuidarte en este momento:',
      'Respire fundo: inspire por 4 segundos, segure por 4, expire por 6.': 'Respira profundamente: inspira durante 4 segundos, mantén el aire 4 segundos y exhala durante 6.',
      'Converse com alguém de confiança — amiga/o, familiar ou colega.': 'Habla con alguien de confianza: una amistad, familiar o colega.',
      'Anote o que aconteceu: data, hora, local e testemunhas.': 'Anota lo que pasó: fecha, hora, lugar y testigos.',
      'Você tem o direito de dizer não e de buscar ajuda a qualquer momento.': 'Tienes derecho a decir que no y a buscar ayuda en cualquier momento.',
      'O que é o Agosto Lilás?': '¿Qué es Agosto Lila?',
      'Casos que marcaram a história': 'Casos que marcaron la historia',
      'Conhecer casos históricos ajuda a compreender a importância da prevenção, da informação e da rede de proteção.': 'Conocer casos históricos ayuda a comprender la importancia de la prevención, la información y las redes de apoyo.',
      'Importante:': 'Importante:',
      'Meu Caso — Estou em situação de assédio?': 'Mi situación — ¿Estoy sufriendo acoso?',
      'apenas orientativo': 'solo orientativo',
      'Pergunta': 'Pregunta',
      'de': 'de',
      'Sim, frequentemente': 'Sí, con frecuencia',
      'Às vezes': 'A veces',
      'Não': 'No',
      'Sim, sempre': 'Sí, siempre',
      'Sim': 'Sí',
      'Já aconteceu uma vez': 'Ocurrió una vez',
      'Sim, com frequência': 'Sí, con frecuencia',
      'Raramente': 'Rara vez',
      'Sim, muito': 'Sí, mucho',
      'Um pouco': 'Un poco',
      'Às vezes tenta': 'A veces lo intenta',
      'Sim, me culpo muito': 'Sí, me culpo mucho',
      'Ver Resultado ✓': 'Ver resultado ✓',
      'Próxima →': 'Siguiente →',
      '← Anterior': '← Anterior',
      'Situação aparentemente segura': 'La situación parece segura',
      'Sinal de atenção — fique alerta': 'Señal de atención — mantente alerta',
      'Indicadores de assédio ou violência': 'Posibles señales de acoso o violencia',
      'Ligue': 'Llama al',
      'agora ou acesse': 'ahora o visita',
      'Refazer': 'Rehacer',
      'Linhas de Apoio 24h': 'Líneas de ayuda 24 h',
      'Toque em uma opção para ligar agora.': 'Toca una opción para llamar ahora.',
      'Ligar agora': 'Llamar ahora',
      'Criar Alerta de Abuso': 'Crear una alerta de abuso',
      'Registre uma situação de risco para alertar outras pessoas. Não inclua dados pessoais de vítimas.': 'Registra una situación de riesgo para alertar a otras personas. No incluyas datos personales de las víctimas.',
      'Tipo de abuso': 'Tipo de abuso',
      'Selecione...': 'Selecciona...',
      'Cidade': 'Ciudad',
      'Estado': 'Estado',
      'Local específico (opcional)': 'Lugar específico (opcional)',
      'Descreva a situação': 'Describe la situación',
      'Nível de urgência': 'Nivel de urgencia',
      'Baixa': 'Baja',
      'Média': 'Media',
      'Alta — risco imediato': 'Alta — riesgo inmediato',
      'Publicar Alerta': 'Publicar alerta',
      'Todos': 'Todos',
      'Sexual': 'Sexual',
      'Moral': 'Psicológico',
      'Violência': 'Violencia',
      'Virtual': 'Virtual',
      'Urgentes': 'Urgentes',
      'Confirmar': 'Confirmar',
      'Nenhum alerta encontrado para este filtro.': 'No se encontraron alertas para este filtro.',
      'Carregando alertas da rede...': 'Cargando alertas de la comunidad...',
      'agora mesmo': 'ahora mismo',
      'min atrás': 'min atrás',
      'Linha do Tempo': 'Línea de tiempo',
      'Delegacias da Mulher (DEAM)': 'Comisarías de la Mujer (DEAM)',
      'Encontre a DEAM mais próxima. Clique no marcador para ver endereço e telefone.': 'Encuentra la DEAM más cercana. Selecciona el marcador para ver la dirección y el teléfono.',
      'Clique no marcador para ver telefone e endereço': 'Selecciona el marcador para ver el teléfono y la dirección',
      'Violeta': 'Violeta',
      'Assistente da Rede Violeta · Online 💜': 'Asistente de Rede Violeta · En línea 💜',
      'Fale com a Violeta...': 'Habla con Violeta...',
      'Enviar': 'Enviar',
      'Ativar respostas faladas da Violeta': 'Activar respuestas habladas de Violeta',
      'Desativar respostas faladas da Violeta': 'Desactivar respuestas habladas de Violeta',
      'Falar com a Violeta usando o microfone': 'Habla con Violeta usando el micrófono',
      'Violeta está digitando…': 'Violeta está escribiendo…',
      'Seu navegador não oferece entrada por voz. Você pode digitar sua mensagem.': 'Tu navegador no permite usar la voz. Puedes escribir tu mensaje.',
      'O acesso ao microfone foi bloqueado. Você pode digitar sua mensagem.': 'Se bloqueó el acceso al micrófono. Puedes escribir tu mensaje.',
      'Não foi possível usar o microfone. Você pode digitar sua mensagem.': 'No se pudo usar el micrófono. Puedes escribir tu mensaje.',
      'Não foi possível iniciar o microfone. Verifique a permissão do navegador ou digite sua mensagem.': 'No se pudo iniciar el micrófono. Revisa los permisos del navegador o escribe tu mensaje.',
      'Olá! 💜 Sou a Violeta, assistente da Rede Violeta. Posso ajudar você a encontrar informações sobre os canais de emergência, explicar os recursos do site ou conversar sobre situações de violência. Se houver perigo imediato, procure um local seguro e ligue 190.': '¡Hola! 💜 Soy Violeta, la asistente de Rede Violeta. Puedo ayudarte a encontrar teléfonos de emergencia, explicar los recursos del sitio o hablar sobre situaciones de violencia. Si estás en peligro inmediato, busca un lugar seguro y llama al 190.',
      'Projeto Acadêmico — Rede Violeta': 'Proyecto académico — Rede Violeta',
      'A Rede Violeta não substitui serviços públicos, atendimento policial, médico, psicológico ou jurídico profissional.': 'Rede Violeta no sustituye los servicios públicos ni la atención policial, médica, psicológica o jurídica profesional.',
      'Suas informações são tratadas com sigilo absoluto.': 'Tu información se trata de forma confidencial.',
      'Central da Mulher': 'Línea de atención a mujeres',
      'Polícia': 'Policía',
      'Direitos Humanos': 'Derechos Humanos',
      'Sair rapidamente deste site e ir para uma página neutra': 'Salir rápidamente de este sitio e ir a una página neutral',
      'Abrir opções de acessibilidade': 'Abrir opciones de accesibilidad',
      'Fechar opções de acessibilidade': 'Cerrar opciones de accesibilidad',
      'Diminuir fonte': 'Reducir el tamaño de fuente',
      'Fonte padrão': 'Tamaño de fuente predeterminado',
      'Aumentar fonte': 'Aumentar el tamaño de fuente',
      'Ativar alto contraste': 'Activar alto contraste',
      'Ativar leitura de conteúdo em voz alta ao clicar nos textos': 'Activar la lectura en voz alta al pulsar los textos',
      'Pausar animações e transições': 'Pausar animaciones y transiciones',
      'Destacar foco do teclado': 'Resaltar el foco del teclado',
      'Telefone': 'Teléfono',
      'Endereço': 'Dirección',
      'Canais de apoio 24h — Agosto Lilás pelo seu direito de dizer NÃO': 'Líneas de ayuda 24 h — Agosto Lila y tu derecho a decir NO',
      'é um projeto acadêmico criado para informar,\n        acolher e apresentar caminhos de apoio para mulheres que estejam passando\n        por situações de violência.': 'es un proyecto académico creado para informar, apoyar y ofrecer recursos a mujeres que atraviesan situaciones de violencia.',
      'Busque apoio psicológico; muitas cidades oferecem serviço gratuito (CAPS).': 'Busca apoyo psicológico; muchas ciudades ofrecen servicios gratuitos (CAPS).',
      'é um movimento nacional de conscientização contra a violência doméstica e sexual. Instituído em agosto — mês da Lei Maria da Penha (Lei nº 11.340/2006, sancionada em 07/08/2006) — o movimento usa o roxo/lilás como símbolo de resistência e esperança.': 'es un movimiento nacional de concienciación contra la violencia doméstica y sexual. Se celebra en agosto, el mes de la Ley Maria da Penha (Ley n.º 11.340/2006, promulgada el 7 de agosto de 2006), y utiliza el morado y el lila como símbolos de resistencia y esperanza.',
      '1 mulher é vítima de violência a cada 6 minutos': 'Una mujer sufre violencia cada 6 minutos',
      '. Falar sobre isso é o primeiro passo para mudar.': '. Hablar de ello es el primer paso para cambiar.',
      'A socialite mineira foi assassinada pelo então namorado. O julgamento provocou grande debate social sobre a culpabilização da vítima e impulsionou discussões importantes sobre a violência contra mulheres.': 'La socialité de Minas Gerais fue asesinada por su entonces novio. El juicio generó un amplio debate social sobre la culpabilización de la víctima e impulsó conversaciones importantes sobre la violencia contra las mujeres.',
      '💜 O caso contribuiu para debates históricos sobre violência contra mulheres e sobre argumentos que culpabilizam vítimas.': '💜 El caso contribuyó a debates históricos sobre la violencia contra las mujeres y los argumentos que culpabilizan a las víctimas.',
      'A atriz e bailarina foi assassinada em 1992. O caso provocou grande mobilização social e a participação de sua mãe, Gloria Perez, em mudanças na legislação penal.': 'La actriz y bailarina fue asesinada en 1992. El caso provocó una gran movilización social y la participación de su madre, Gloria Perez, en cambios de la legislación penal.',
      '💜 O caso mostra como a mobilização social pode contribuir para mudanças importantes na legislação.': '💜 El caso muestra cómo la movilización social puede contribuir a cambios importantes en la legislación.',
      'Aos 15 anos, Eloá foi mantida em cárcere privado pelo ex-namorado em Santo André, SP. O caso teve grande repercussão nacional e o agressor foi condenado a 98 anos e 8 meses.': 'A los 15 años, Eloá fue mantenida cautiva por su exnovio en Santo André, São Paulo. El caso tuvo repercusión nacional y el agresor fue condenado a 98 años y 8 meses.',
      '💜 O caso reforça a importância de reconhecer situações de controle e ameaça e buscar ajuda.': '💜 El caso refuerza la importancia de reconocer situaciones de control y amenaza y buscar ayuda.',
      'Eliza desapareceu em 2010. O caso envolveu o então goleiro Bruno Fernandes e teve grande repercussão nacional, evidenciando a importância de redes de proteção.': 'Eliza desapareció en 2010. El caso involucró al entonces portero Bruno Fernandes y tuvo gran repercusión nacional, mostrando la importancia de las redes de apoyo.',
      'A advogada foi assassinada em 2010. O caso foi julgado pelo Tribunal do Júri de Guarulhos — primeiro julgamento televisionado ao vivo no Brasil. O agressor foi condenado a 22 anos e 8 meses.': 'La abogada fue asesinada en 2010. El caso fue juzgado por el tribunal del jurado de Guarulhos, el primer juicio transmitido en directo en Brasil. El agresor fue condenado a 22 años y 8 meses.',
      'Assédio é qualquer comportamento indesejado que cause constrangimento, humilhação, intimidação ou sofrimento. Pode ser físico, verbal, virtual ou psicológico.': 'El acoso es cualquier comportamiento no deseado que cause vergüenza, humillación, intimidación o sufrimiento. Puede ser físico, verbal, virtual o psicológico.',
      'é culpa de quem sofre. Independentemente de roupa, comportamento ou relação com o agressor.': 'es culpa de quien agrede, independientemente de la ropa, el comportamiento o la relación con el agresor.',
      'Exposição repetida a situações humilhantes ou constrangedoras no ambiente de trabalho.': 'Exposición repetida a situaciones humillantes o incómodas en el trabajo.',
      'Ser ignorada/o sistematicamente por colegas ou superiores.': 'Ser ignorada/o sistemáticamente por colegas o superiores.',
      'Receber tarefas impossíveis de cumprir para ser culpabilizada/o.': 'Recibir tareas imposibles de cumplir para luego ser culpabilizada/o.',
      'Sofrer piadas, apelidos ofensivos ou humilhações na frente de outros.': 'Sufrir bromas, apodos ofensivos o humillaciones delante de otras personas.',
      'Ter méritos negados ou trabalho atribuído a outra pessoa.': 'Que se nieguen tus méritos o se atribuya tu trabajo a otra persona.',
      'Ameaças constantes de demissão sem motivo justificado.': 'Amenazas constantes de despido sin motivo justificado.',
      'Isolamento forçado ou retirada de responsabilidades sem explicação.': 'Aislamiento forzado o retirada de responsabilidades sin explicación.',
      'Conduta de natureza sexual não desejada, que constranja ou cause desconforto.': 'Conducta sexual no deseada que cause vergüenza o incomodidad.',
      'Comentários, piadas ou insinuações de cunho sexual.': 'Comentarios, bromas o insinuaciones de carácter sexual.',
      'Toques não consentidos em qualquer parte do corpo.': 'Toques no consentidos en cualquier parte del cuerpo.',
      'Convites insistentes para encontros após rejeição clara.': 'Invitaciones insistentes a citas después de una negativa clara.',
      'Envio de imagens, vídeos ou mensagens de conteúdo sexual não solicitado.': 'Envío de imágenes, videos o mensajes sexuales no solicitados.',
      'Chantagem com vantagens profissionais em troca de favores sexuais.': 'Chantaje con ventajas profesionales a cambio de favores sexuales.',
      'Perseguição, humilhação ou ameaças realizadas por meios digitais.': 'Persecución, humillación o amenazas realizadas por medios digitales.',
      'Mensagens ofensivas, ameaças ou difamação em redes sociais.': 'Mensajes ofensivos, amenazas o difamación en redes sociales.',
      'Compartilhamento de fotos ou vídeos íntimos sem consentimento (revenge porn).': 'Compartir fotos o videos íntimos sin consentimiento (difusión no consentida de imágenes íntimas).',
      'Monitoramento excessivo de perfis, localização ou atividades online.': 'Vigilancia excesiva de perfiles, ubicación o actividades en internet.',
      'Comportamentos controladores e abusivos dentro de relações familiares ou afetivas.': 'Comportamientos controladores y abusivos en relaciones familiares o afectivas.',
      'Controle de com quem você fala, sai ou se relaciona.': 'Controlar con quién hablas, sales o te relacionas.',
      'Críticas constantes, xingamentos ou desvalorização.': 'Críticas constantes, insultos o menosprecio.',
      'Ameaças veladas ou explícitas de agressão física.': 'Amenazas veladas o explícitas de agresión física.',
      'Controle financeiro — impedir acesso ao próprio dinheiro.': 'Control financiero: impedir el acceso al propio dinero.',
      'Comportamento agressivo e repetitivo contra estudantes em ambiente escolar.': 'Comportamiento agresivo y repetido contra estudiantes en el entorno escolar.',
      'Sinais de alerta em você mesma/o': 'Señales de alerta que puedes notar',
      'Se você está passando por assédio, pode notar alguns desses efeitos:': 'Si estás sufriendo acoso, puedes notar algunos de estos efectos:',
      'Ansiedade ou medo constante': 'Ansiedad o miedo constante',
      'Dores físicas sem causa aparente': 'Dolores físicos sin causa aparente',
      'Dificuldade de concentração': 'Dificultad para concentrarse',
      'O que fazer se isso acontecer comigo?': '¿Qué puedo hacer si me ocurre?',
      '— especialmente se houver risco de violência.': '— especialmente si existe riesgo de violencia.',
      '— alguém que tenha presenciado situações.': '— alguien que haya presenciado la situación.',
      '— RH, direção escolar, conselho tutelar, etc.': '— Recursos Humanos, dirección escolar, servicios de protección infantil, etc.',
      'Registre boletim de ocorrência': 'Presenta una denuncia policial',
      '— na delegacia da mulher ou online.': '— en una comisaría de la mujer o por internet.',
      'Procure apoio jurídico e psicológico': 'Busca apoyo jurídico y psicológico',
      'Eventos históricos relevantes para a legislação de proteção à mulher.': 'Acontecimientos históricos relevantes para las leyes de protección a las mujeres.',
      'Responda as perguntas abaixo com sinceridade. O resultado é': 'Responde las siguientes preguntas con sinceridad. El resultado es',
      'e não substitui apoio profissional.': 'y no sustituye el apoyo profesional.',
      '1. Alguém faz comentários, piadas ou gestos de conteúdo sexual ou íntimo sem sua permissão?': '1. ¿Alguien hace comentarios, bromas o gestos sexuales o íntimos sin tu consentimiento?',
      '2. Você sente medo ou ansiedade quando vai ao trabalho, escola ou se relaciona com alguém específico?': '2. ¿Sientes miedo o ansiedad al ir al trabajo, a la escuela o al relacionarte con alguien en particular?',
      '3. Alguém te pressiona, chantageia ou ameaça para obter algum favor, presença ou contato?': '3. ¿Alguien te presiona, chantajea o amenaza para obtener un favor, tu presencia o contacto?',
      '4. Você recebe mensagens, ligações ou contatos insistentes mesmo depois de pedir que parem?': '4. ¿Recibes mensajes, llamadas o contactos insistentes después de pedir que paren?',
      '5. Alguém te humilha, grita, te diminui ou critica na frente de outras pessoas?': '5. ¿Alguien te humilla, te grita, te menosprecia o te critica delante de otras personas?',
      '6. Você evita certos lugares, situações ou pessoas por se sentir insegura/o?': '6. ¿Evitas ciertos lugares, situaciones o personas porque te sientes insegura/o?',
      '7. Alguém controla o que você faz, com quem fala, onde vai ou como se veste?': '7. ¿Alguien controla lo que haces, con quién hablas, adónde vas o cómo te vistes?',
      '8. Você se culpa por situações em que foi tratada/o de forma desrespeitosa?': '8. ¿Te culpas por situaciones en las que te trataron sin respeto?',
      'Orientação, denúncia e encaminhamento. Gratuito, 24h.': 'Orientación, denuncias y derivación. Gratis, las 24 horas.',
      'Emergências e ocorrências em andamento.': 'Emergencias e incidentes en curso.',
      'Violações de direitos, inclusive crianças e adolescentes.': 'Violaciones de derechos, incluidos niños y adolescentes.',
      'Assistência jurídica gratuita para quem não pode pagar advogado.': 'Asistencia jurídica gratuita para quienes no pueden pagar un abogado.',
      'Apoio Psicológico Gratuito': 'Apoyo psicológico gratuito',
      'Acesse os sites oficiais para encontrar atendimento perto de você.': 'Visita los sitios oficiales para encontrar atención cerca de ti.',
      'Denúncia e apoio para crimes e violências na internet.': 'Denuncias y apoyo ante delitos y violencia en internet.',
      'Nenhuma pergunta encontrada. Tente outro termo.': 'No se encontraron preguntas. Prueba con otro término.',
      'Onde e como o assédio mais acontece': 'Dónde y cómo ocurre el acoso con más frecuencia',
      'Fórum Brasileiro de Segurança Pública 2025': 'Foro Brasileño de Seguridad Pública 2025',
      'Este site foi desenvolvido como projeto acadêmico para a Faculdade Cruzeiro do Sul, com finalidade educativa e de conscientização sobre violência contra a mulher.': 'Este sitio se desarrolló como proyecto académico para la Faculdade Cruzeiro do Sul con fines educativos y de concienciación sobre la violencia contra las mujeres.',
      '🎙️ Ouvindo... fale agora.': '🎙️ Escuchando... habla ahora.',
      'Selecione uma opção antes de avançar.': 'Selecciona una opción antes de continuar.',
      'Escreva algo antes de registrar seu desabafo. 💙': 'Escribe algo antes de enviar tu mensaje. 💙',
      'Suas respostas não indicam sinais fortes de assédio no momento. Continue atenta/o e lembre-se: qualquer desconforto merece atenção. Fique segura/o e cuide-se!': 'Tus respuestas no indican señales claras de acoso en este momento. Mantente alerta y recuerda: cualquier incomodidad merece atención. ¡Cuídate!',
      'Suas respostas indicam situações que merecem atenção. Algumas experiências que você relatou podem configurar assédio. Conversar com alguém de confiança ou um profissional pode ajudar a esclarecer a situação.': 'Tus respuestas indican situaciones que merecen atención. Algunas experiencias que describiste podrían constituir acoso. Hablar con alguien de confianza o con un profesional puede ayudarte a aclarar la situación.',
      'Suas respostas indicam que você pode estar em situação de assédio ou violência. Você não está sozinha/o e há apoio disponível. Busque ajuda agora — use os canais abaixo ou a aba Fazer Denúncia.': 'Tus respuestas indican que podrías estar sufriendo acoso o violencia. No estás sola y hay apoyo disponible. Busca ayuda ahora mediante los contactos de abajo o la pestaña de denuncias.',
      'Violência Doméstica': 'Violencia doméstica',
      'Assédio Sexual': 'Acoso sexual',
      'Assédio Moral': 'Acoso laboral',
      'Assédio Virtual / Cyberbullying': 'Acoso virtual / ciberacoso',
      'Perseguição (Stalking)': 'Persecución (stalking)',
      'Importunação Sexual': 'Acoso sexual',
      'Violência Física': 'Violencia física',
      'Assédio Virtual (Cyberbullying / Stalking Online)': 'Acoso virtual (ciberacoso / persecución en línea)',
      'Assédio Doméstico / Familiar': 'Abuso doméstico / familiar',
      'Assédio Escolar (Bullying)': 'Acoso escolar (bullying)',
      'CAPS — Centro de Atenção Psicossocial': 'CAPS — Centro de Atención Psicosocial',
      'UBS — Unidade Básica de Saúde': 'UBS — Unidad Básica de Salud',
      'Delegacia da Mulher (DEAM)': 'Comisaría de la Mujer (DEAM)',
      'O que diferencia assédio de violência?': '¿Cuál es la diferencia entre acoso y violencia?',
      'Posso denunciar de forma anônima?': '¿Puedo denunciar de forma anónima?',
      'Preciso de advogado para denunciar?': '¿Necesito un abogado para denunciar?',
      'A Lei Maria da Penha protege apenas mulheres cisgênero?': '¿La Ley Maria da Penha protege solo a mujeres cisgénero?',
      'O que acontece depois que eu denuncio?': '¿Qué pasa después de presentar una denuncia?',
      'Posso retirar uma denúncia depois?': '¿Puedo retirar una denuncia después?',
      'Como provar assédio no trabalho?': '¿Cómo puedo demostrar el acoso laboral?',
      'O que é uma Medida Protetiva de Urgência?': '¿Qué es una medida de protección urgente?',
      'Assédio virtual / online é crime?': '¿El acoso virtual o en línea es un delito?',
      'Você pode mudar essa opção depois.': 'Puedes cambiar esta opción más adelante.',
      'Mudar idioma': 'Cambiar idioma',
      'Indicadores de segurança': 'Indicadores de seguridad',
      'AGOSTO LILÁS 2026': 'AGOSTO LILA 2026',
      'Agosto Lilás 2026': 'Agosto Lila 2026',
      'Agosto Lilás': 'Agosto Lila',
      'O que é assédio?': '¿Qué es el acoso?',
      'é um comportamento repetido e indesejado de natureza sexual, moral ou psicológica.': 'es un comportamiento repetido e indeseado de carácter sexual, laboral o psicológico.',
      'pode ser um único ato físico, sexual, psicológico, patrimonial ou moral.': 'puede consistir en un solo acto físico, sexual, psicológico, patrimonial o moral.',
      'Ambos são crimes — a diferença está na forma e na frequência, mas os dois merecem denúncia.': 'Ambos pueden ser delitos. Se diferencian por la forma y la frecuencia, pero los dos merecen ser denunciados.',
      'aceitam denúncias anônimas. A identidade não é necessária para que a denúncia seja investigada.': 'aceptan denuncias anónimas. No es necesario revelar tu identidad para que se investigue.',
      'Você pode registrar sozinha/o na delegacia ou online. Para processos judiciais é recomendado, mas a': 'Puedes presentar una denuncia por tu cuenta en una comisaría o por internet. Se recomienda contar con representación legal en los procesos judiciales, pero la',
      'oferece assistência jurídica': 'ofrece asistencia jurídica',
      'para quem não tem condições de contratar advogado particular.': 'a quienes no pueden pagar un abogado particular.',
      'O STJ e o STF entendem que a Lei Maria da Penha protege': 'Los tribunales superiores de Brasil han determinado que la Ley Maria da Penha protege',
      ', pois o critério é gênero feminino, não biológico. Homens cisgêneros podem recorrer ao Código Penal e à Lei nº 13.772/2018 em casos de violência doméstica.': ', porque el criterio es el género femenino, no el sexo biológico. Los hombres cisgénero pueden recurrir al Código Penal y a la Ley n.º 13.772/2018 en casos de violencia doméstica.',
      '1. A delegacia abre um Inquérito Policial.': '1. La policía inicia una investigación.',
      '2. O Ministério Público recebe o inquérito e pode oferecer denúncia criminal.': '2. La Fiscalía recibe la investigación y puede presentar cargos penales.',
      '3. Você pode solicitar': '3. Puedes solicitar',
      'Medidas Protetivas de Urgência': 'Medidas de protección urgentes',
      '4. O juiz decide sobre as medidas em até 48h.': '4. Un juez decide sobre las medidas en un plazo de 48 horas.',
      'não pode ser retirada': 'no puede ser retirada',
      'pela vítima após o processo iniciado — cabe ao Estado prosseguir. Isso protege a vítima de pressões do agressor. A retratação só é possível antes do recebimento da denúncia pelo juiz, mediante audiência.': 'por la víctima una vez iniciado el proceso; corresponde al Estado continuar el caso. Esto protege a la víctima de las presiones del agresor. Solo es posible retractarse antes de que un juez admita los cargos y mediante una audiencia.',
      'Guarde prints de mensagens, e-mails, registros de chamadas. Anote datas, horários e o que foi dito. Identifique testemunhas. Registre ocorrência no RH com protocolo. Em seguida, procure a Delegacia do Trabalho (MTE) ou ajuíze ação na Justiça do Trabalho. O assédio moral é ilícito civil (art. 186 CC) e pode resultar em demissão por justa causa do agressor.': 'Guarda capturas de pantalla de mensajes, correos y llamadas. Anota fechas, horas y lo ocurrido, e identifica a los testigos. Presenta una queja documentada ante Recursos Humanos y luego acude al Ministerio de Trabajo o presenta una demanda laboral. El acoso laboral es un ilícito civil y puede causar el despido justificado del agresor.',
      'É uma determinação judicial que pode: proibir o agressor de se aproximar da vítima; proibi-lo de contato por qualquer meio; retirá-lo do lar; suspender porte de arma. É solicitada ao registrar o B.O. e decidida pelo juiz em até 48 horas. Descumprir medida protetiva é crime com pena de 3 meses a 2 anos de prisão (art. 24-A da Lei Maria da Penha).': 'Es una orden judicial que puede prohibir al agresor acercarse o contactar a la víctima, expulsarlo del hogar o suspender su permiso de armas. Puede solicitarse al presentar la denuncia y un juez decide en un plazo de 48 horas. Incumplir una medida de protección es un delito castigado con entre 3 meses y 2 años de prisión, según el artículo 24-A de la Ley Maria da Penha.',
      'Sim. A Lei nº 13.772/2018 criminaliza o registro não autorizado de conteúdo íntimo. A Lei nº 13.718/2018 criou o crime de importunação sexual online. Compartilhamento de fotos íntimas sem consentimento (revenge porn) é crime com pena de 1 a 5 anos. Denuncie também pelo SaferNet.': 'Sí. La Ley n.º 13.772/2018 penaliza la grabación no autorizada de contenido íntimo. La Ley n.º 13.718/2018 tipificó el acoso sexual en línea. Compartir imágenes íntimas sin consentimiento también es delito, con penas de 1 a 5 años. También puedes denunciarlo en SaferNet.',
      'Criação de perfis falsos para assediar ou difamar.': 'Creación de perfiles falsos para acosar o difamar.',
      'Exclusão social online organizada por um grupo.': 'Exclusión social en línea organizada por un grupo.',
      'Ciúmes excessivos e cobranças de localização a todo momento.': 'Celos excesivos y exigencias constantes de compartir tu ubicación.',
      'Apelidos ofensivos, ridicularização ou exclusão do grupo.': 'Apodos ofensivos, burlas o exclusión del grupo.',
      'Agressões físicas, empurrões ou destruição de objetos.': 'Agresiones físicas, empujones o destrucción de objetos.',
      'Ameaças ou chantagem por materiais escolares, dinheiro ou favores.': 'Amenazas o chantaje por útiles escolares, dinero o favores.',
      'Difamação ou fofocas para isolar a vítima socialmente.': 'Difamación o rumores para aislar socialmente a la víctima.',
      'Insônia ou pesadelos': 'Insomnio o pesadillas',
      '— salve prints, e-mails, mensagens, datas e horários.': '— guarda capturas, correos, mensajes, fechas y horas.',
      'Não confronte sozinha/o': 'No te enfrentes a esa persona a solas',
      'Comunique à instituição': 'Informa a la institución',
      '188 — CVV': '188 — CVV',
      'Centro de Valorização da Vida. Escuta e apoio emocional.': 'Centro de Valoración de la Vida de Brasil. Escucha y apoyo emocional.',
      'Apoio Jurídico Gratuito': 'Apoyo jurídico gratuito',
      'Defensoria Pública': 'Defensoría Pública',
      'OAB — Ordem dos Advogados': 'OAB — Colegio de Abogados de Brasil',
      'Núcleos de prática jurídica e atendimento pro bono em muitas seccionais.': 'Muchas sedes ofrecen clínicas jurídicas y servicios gratuitos.',
      'Núcleos Universitários': 'Clínicas jurídicas universitarias',
      'Clínicas jurídicas de faculdades oferecem atendimento gratuito supervisionado.': 'Las facultades de Derecho ofrecen atención gratuita supervisada.',
      'Serviço público gratuito de saúde mental. Para orientação, ligue 136 (Disque Saúde).': 'Servicio público gratuito de salud mental. Para orientación, llama al 136 (Línea de Salud).',
      'Centro de Referência em Assistência Social. Para localizar atendimento, ligue 121 (Disque Social).': 'Centro de Referencia de Asistencia Social. Para encontrar atención, llama al 121 (Línea Social).',
      'Solicite encaminhamento para psicólogo pelo SUS. Para orientação, ligue 136 (Disque Saúde).': 'Solicita una derivación a psicología a través del sistema público de salud (SUS). Para orientación, llama al 136.',
      'Registro discreto de ocorrências diretamente pelo celular.': 'Registra incidentes discretamente desde tu teléfono.',
      'denúncias e orientações online.': 'denuncias y orientación en línea.',
      'Consulta gratuita de processos e orientações jurídicas.': 'Consulta gratuita de procesos e información jurídica.',
      'O Agosto Lilás': 'Agosto Lila',
      '💜 A história reforça a importância de redes de proteção e de canais para pedir ajuda.': '💜 Esta historia destaca la importancia de las redes de apoyo y de los canales para pedir ayuda.',
      '💜 O caso evidencia a importância da investigação, da Justiça e do acolhimento às famílias das vítimas.': '💜 Este caso destaca la importancia de la investigación, la justicia y el apoyo a las familias de las víctimas.',
      'os casos apresentados são fatos históricos utilizados exclusivamente para fins educativos e de conscientização.': 'los casos presentados son hechos históricos utilizados exclusivamente con fines educativos y de concienciación.',
      'Especializada em violência doméstica. Ligue 180 para localizar a mais próxima.': 'Especializada en violencia doméstica. Llama al 180 para encontrar la más cercana.',
      '— muitos são gratuitos.': '— muchos son gratuitos.',
      'dos casos de violência ocorrem na': 'de los casos de violencia ocurren en la',
      'residência': 'vivienda',
      'da vítima': 'de la víctima',
      'acontecem em': 'ocurren en',
      'vias públicas': 'la vía pública',
      ', ruas e espaços abertos': ', calles y espacios abiertos',
      'dos agressores são': 'de los agresores son',
      'parceiros ou ex-parceiros': 'parejas o exparejas',
      'Residência — 65%': 'Vivienda — 65%',
      'Principal cenário de violência doméstica e psicológica. A vítima convive com o agressor.': 'Principal escenario de violencia doméstica y psicológica. La víctima convive con el agresor.',
      'Via pública — 13%': 'Vía pública — 13%',
      'Ruas, praças, feiras e pontos de ônibus. Maior incidência nos horários de pico.': 'Calles, plazas, mercados y paradas de autobús. Hay más casos en las horas punta.',
      'Praticado por colegas, superiores ou clientes. Muitas vezes silenciado por medo de demissão.': 'Cometido por colegas, superiores o clientes. A menudo se silencia por miedo a perder el empleo.',
      'Transporte público — 4%': 'Transporte público — 4%',
      'Metrô, ônibus e terminais. Especialmente intenso nos horários de pico.': 'Metro, autobuses y terminales. Es más frecuente en las horas punta.',
      'Afeta principalmente jovens e adolescentes; pode começar no ambiente virtual.': 'Afecta principalmente a jóvenes y adolescentes; puede comenzar en internet.',
      '— Metrô Linha 2-Verde': '— Metro, línea verde 2',
      'Relatos recorrentes de importunação sexual nos vagões entre as estações Paraíso e Ana Rosa nos horários de pico.': 'Denuncias recurrentes de acoso sexual en los vagones entre las estaciones Paraíso y Ana Rosa durante las horas punta.',
      '1h atrás': 'hace 1 h',
      '— Bairro Água Verde': '— barrio Água Verde',
      'Homem seguindo mulheres que saem do trabalho no período noturno. Comportamento identificado em mais de uma ocasião.': 'Un hombre sigue a mujeres que salen del trabajo por la noche. Se ha reportado este comportamiento en más de una ocasión.',
      '— Bairro Santa Efigênia': '— barrio Santa Efigênia',
      'Situação de violência doméstica em andamento relatada por vizinhas. Pedido de apoio e orientação à comunidade.': 'Vecinas reportaron una situación de violencia doméstica en curso y solicitaron apoyo y orientación a la comunidad.',
      '2h atrás': 'hace 2 h',
      '— Setor Bancário Sul — empresa privada': '— Sector Bancario Sur — empresa privada',
      'Supervisora humilha funcionárias publicamente em reuniões, atribui erros alheios a elas e ameaça demissão sem justificativa. Pelo menos 5 relatos confirmados.': 'Una supervisora humilla públicamente a sus empleadas en reuniones, les atribuye errores ajenos y amenaza con despedirlas sin justificación. Se confirmaron al menos cinco denuncias.',
      '3h atrás': 'hace 3 h',
      'Grupo no Telegram compartilha fotos e vídeos íntimos de mulheres sem consentimento. Vítimas identificadas já acionaram a SaferNet.': 'Un grupo de Telegram comparte fotos y videos íntimos de mujeres sin su consentimiento. Las víctimas identificadas ya contactaron a SaferNet.',
      '4h atrás': 'hace 4 h',
      'Perfis falsos criados para assediar mulheres com mensagens íntimas não solicitadas. Múltiplas vítimas relataram o mesmo padrão.': 'Se crearon perfiles falsos para acosar a mujeres con mensajes íntimos no solicitados. Varias víctimas denunciaron el mismo patrón.',
      '5h atrás': 'hace 5 h',
      'Assédio': 'Acoso',
      'O assédio nunca': 'El acoso nunca',
      'prints de mensagens': 'capturas de mensajes',
      'testemunhas': 'testigos',
      'É uma determinação judicial que pode: proibir o agressor de se aproximar da vítima; proibi-lo de contato por qualquer meio; retirá-lo do lar; suspender porte de arma. É solicitada ao registrar o B.O. e decidida pelo juiz em até': 'Es una orden judicial que puede prohibir al agresor acercarse o contactar a la víctima, expulsarlo del hogar o suspender su permiso de armas. Puede solicitarse al presentar la denuncia y un juez decide en un plazo de',
      'Descumprir medida protetiva é crime com pena de 3 meses a 2 anos de prisão (art. 24-A da Lei Maria da Penha).': 'Incumplir una medida de protección es un delito castigado con entre 3 meses y 2 años de prisión, según el artículo 24-A de la Ley Maria da Penha.',
      'criminaliza o registro não autorizado de conteúdo íntimo. A': 'penaliza la grabación no autorizada de contenido íntimo. La Ley n.º 13.718/2018',
      'criou o crime de importunação sexual online. Compartilhamento de fotos íntimas sem consentimento (': 'tipificó el acoso sexual en línea. Compartir imágenes íntimas sin consentimiento (',
      ') é crime com pena de 1 a 5 anos. Denuncie também pelo': ') es delito, con penas de 1 a 5 años. También puedes denunciarlo en',
      'O assédio moral é ilícito civil': 'El acoso laboral es un ilícito civil',
      'Sim. A': 'Sí. La',
      'Não para o Boletim de Ocorrência.': 'No, no es necesario para presentar una denuncia policial.',
      'gratuita': 'gratuita',
      'mulheres trans e travestis': 'mujeres trans y travestis',
      'Inquérito Policial': 'investigación policial',
      'ação penal pública': 'acción penal pública',
      '(como os previstos na Lei Maria da Penha), a denúncia': '(como los previstos en la Ley Maria da Penha), la denuncia',
      'Justiça do Trabalho': 'Justicia Laboral',
      'Não.': 'No.',
      '6h atrás': 'hace 6 h',
      '8h atrás': 'hace 8 h',
      '10h atrás': 'hace 10 h',
      '16h atrás': 'hace 16 h',
      '18h atrás': 'hace 18 h',
      '20h atrás': 'hace 20 h',
      '1d atrás': 'hace 1 día',
      'Homem encosta e faz comentários obscenos em mulheres que aguardam ônibus no período da tarde. Relatado por passageiras em diferentes dias.': 'Un hombre toca a mujeres y les hace comentarios obscenos mientras esperan el autobús por la tarde. Pasajeras lo denunciaron en distintos días.',
      'Mulher agredida fisicamente por parceiro em via pública. Vizinhos chamaram a PM. Vítima está em abrigo. Caso em acompanhamento pela Delegacia da Mulher.': 'Una mujer fue agredida físicamente por su pareja en la vía pública. Los vecinos llamaron a la policía. Está en un refugio y la Comisaría de la Mujer sigue el caso.',
      'Ex-aluno persegue estudante dentro do campus, manda mensagens ameaçadoras e aparece em locais que ela frequenta. Caso registrado na ouvidoria da universidade.': 'Un exalumno persigue a una estudiante en el campus, le envía mensajes amenazantes y aparece en los lugares que frecuenta. El caso se comunicó a la defensoría universitaria.',
      'Grupo de homens abordando mulheres de forma agressiva na orla. Situação especialmente intensa nos finais de semana.': 'Un grupo de hombres aborda agresivamente a mujeres en el paseo costero. La situación empeora especialmente los fines de semana.',
      'Mulher foi agredida com socos pelo companheiro após tentar terminar o relacionamento. Filho menor de idade presenciou. Medida protetiva solicitada.': 'Una mujer recibió golpes de su pareja después de intentar terminar la relación. Su hijo menor presenció la agresión. Se solicitó una medida de protección.',
      'Homens abordam mulheres que estão sozinhas na praia, fazem comentários sexuais e seguem mesmo após pedido de afastamento. Situações repetidas nos fins de semana.': 'Hombres se acercan a mujeres que están solas en la playa, hacen comentarios sexuales y las siguen incluso después de pedirles que se alejen. Ocurre repetidamente los fines de semana.',
      'Mulheres relatam apalpamentos e comentários sexuais na feira, especialmente em dias de maior movimento. Policiamento pedido por feirantes.': 'Mujeres denuncian tocamientos y comentarios sexuales en el mercado, sobre todo en los días de mayor afluencia. Los comerciantes solicitaron más vigilancia policial.',
      'Advogada relata que sócio faz comentários sobre seu corpo e envia mensagens com conotação sexual. Dois outros funcionários testemunharam situações.': 'Una abogada denuncia que un socio hace comentarios sobre su cuerpo y le envía mensajes con insinuaciones sexuales. Otros dos empleados fueron testigos.',
      'Moradora relata agressões verbais e físicas frequentes. Tentou registrar BO, mas se sentiu intimidada. Vizinhos solicitam apoio de assistência social.': 'Una residente denuncia agresiones verbales y físicas frecuentes. Intentó presentar una denuncia, pero se sintió intimidada. Los vecinos solicitan asistencia social.',
      'Funcionárias relatam assédio moral sistemático por parte de gerência. Situação já reportada ao RH sem resolução.': 'Empleadas denuncian acoso laboral sistemático por parte de la gerencia. Ya lo comunicaron a Recursos Humanos, pero no se ha resuelto.',
      'Grupo de alunos cria memes ofensivos com fotos de colegas do sexo feminino e circula em grupos de turma. Direção da escola foi comunicada.': 'Un grupo de estudiantes creó memes ofensivos con fotos de compañeras y los difundió en grupos de clase. Se informó a la dirección de la escuela.',
      '6h atrás': 'hace 6 h',
      '8h atrás': 'hace 8 h',
      '10h atrás': 'hace 10 h',
      '16h atrás': 'hace 16 h',
      '18h atrás': 'hace 18 h',
      '20h atrás': 'hace 20 h',
      'Outro': 'Otro',
      'Alta': 'Alta',
      'Média': 'Media',
      'Baixa': 'Baja'
    }
  };

  const textState = new WeakMap();
  const attributeState = new WeakMap();
  let currentLanguage = 'pt';
  let observer;

  function translateValue(value, language) {
    if (language === 'pt') return value;
    const dictionary = translations[language];
    const trimmed = value.trim();
    if (dictionary[trimmed]) return value.replace(trimmed, dictionary[trimmed]);

    let result = value;
    Object.keys(dictionary).sort((a, b) => b.length - a.length).forEach(function (source) {
      if (source.length > 6 && result.includes(source)) result = result.split(source).join(dictionary[source]);
    });
    return result;
  }

  function translateTextNode(node) {
    const state = textState.get(node);
    const source = state && node.nodeValue === state.rendered ? state.source : node.nodeValue;
    const rendered = translateValue(source, currentLanguage);
    textState.set(node, { source, rendered });
    if (node.nodeValue !== rendered) node.nodeValue = rendered;
  }

  function translateAttributes(element) {
    ['placeholder', 'title', 'aria-label'].forEach(function (name) {
      if (!element.hasAttribute(name)) return;
      let states = attributeState.get(element);
      if (!states) {
        states = {};
        attributeState.set(element, states);
      }
      const state = states[name];
      const current = element.getAttribute(name);
      const source = state && current === state.rendered ? state.source : current;
      const rendered = translateValue(source, currentLanguage);
      states[name] = { source, rendered };
      if (current !== rendered) element.setAttribute(name, rendered);
    });
  }

  function translateTree(root) {
    if (!root) return;
    const walker = document.createTreeWalker(root, NodeFilter.SHOW_TEXT, {
      acceptNode: function (node) {
        const parent = node.parentElement;
        if (!parent || parent.closest('script, style, textarea, input, .simple-user-msg')) {
          return NodeFilter.FILTER_REJECT;
        }
        return node.nodeValue.trim() ? NodeFilter.FILTER_ACCEPT : NodeFilter.FILTER_REJECT;
      }
    });
    const nodes = [];
    while (walker.nextNode()) nodes.push(walker.currentNode);
    nodes.forEach(translateTextNode);
    if (root.nodeType === Node.ELEMENT_NODE) {
      translateAttributes(root);
      root.querySelectorAll('*').forEach(translateAttributes);
    }
  }

  function setSiteLanguage(language) {
    if (!['pt', 'en', 'es'].includes(language)) throw new Error('Idioma não suportado: ' + language);
    currentLanguage = language;
    document.documentElement.lang = language === 'pt' ? 'pt-BR' : language;
    try { localStorage.setItem(STORAGE_KEY, language); } catch (error) {
      console.warn('Não foi possível salvar o idioma selecionado.', error);
    }
    translateTree(document.body);
    const gate = document.getElementById('languageGate');
    if (gate) gate.classList.remove('open');
    document.dispatchEvent(new CustomEvent('site-language-change', { detail: { language } }));
  }

  function showLanguagePicker() {
    const gate = document.getElementById('languageGate');
    if (!gate) return;
    gate.classList.add('open');
    const selected = gate.querySelector('button');
    if (selected) selected.focus();
  }

  function getSiteLanguage() {
    return currentLanguage;
  }

  function translateSiteText(value) {
    return translateValue(String(value), currentLanguage);
  }

  function startLanguageSupport() {
    let savedLanguage = null;
    try { savedLanguage = localStorage.getItem(STORAGE_KEY); } catch (_) {}
    if (['pt', 'en', 'es'].includes(savedLanguage)) {
      currentLanguage = savedLanguage;
      document.documentElement.lang = savedLanguage === 'pt' ? 'pt-BR' : savedLanguage;
      translateTree(document.body);
    } else {
      showLanguagePicker();
    }

    observer = new MutationObserver(function (records) {
      records.forEach(function (record) {
        if (record.type === 'characterData') translateTextNode(record.target);
        record.addedNodes.forEach(function (node) {
          if (node.nodeType === Node.TEXT_NODE) translateTextNode(node);
          else if (node.nodeType === Node.ELEMENT_NODE) translateTree(node);
        });
      });
    });
    observer.observe(document.body, { childList: true, characterData: true, subtree: true });
  }

  window.setSiteLanguage = setSiteLanguage;
  window.showLanguagePicker = showLanguagePicker;
  window.getSiteLanguage = getSiteLanguage;
  window.translateSiteText = translateSiteText;
  window.addEventListener('DOMContentLoaded', startLanguageSupport, { once: true });
}());
